source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'sqlcommenter_rails', path: '../sqlcommenter_rails'
gem 'marginalia', path: '../marginalia'
gem 'marginalia-opencensus', path: '../marginalia-opencensus'

gem 'opencensus', '~> 0.4.0'

# Rails 6.0.0.rc1 --api gems below.

gem 'activerecord', '~> 6.0.0.rc1'
gem 'actionpack', '~> 6.0.0.rc1'
gem 'railties', '~> 6.0.0.rc1'
gem 'bundler', '>= 2.0.1'

gem 'sqlite3', '~> 1.4'
gem 'puma', '>= 3.12.4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
