name: Publish to Sqlcommenter-php repository
on:
  push:
    branches:
      - master
    paths:
      - php/sqlcommenter-php/packages/sqlcommenter-laravel/**
jobs:
  push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PHP_SQLCOMMENTER_PUSH_TOKEN }}
        with:
          source-directory: 'php/sqlcommenter-php/packages/sqlcommenter-laravel'
          destination-github-username: 'google'
          destination-repository-name: 'sqlcommenter-php'
          target-branch: main
