name: Nodejs Knex Packages Test

on:
  push:
    # branches:
    #       - master
    #     paths:
    #       - python/nodejs/packages/**
    #   pull_request:
    #     paths:
    #       - python/nodejs/packages/**

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ current, lts/* ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: nodejs/packages/sqlcommenter-knex
      - run: npm run build --if-present
        working-directory: nodejs/packages/sqlcommenter-knex
      - run: npm test
        working-directory: nodejs/packages/sqlcommenter-knex

      